seed_index: 2
deterministic: False

trainer:
  fast_dev_run: False 
  gpus: 1
  precision: 32
  max_epochs: 250
  max_steps: -1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 10.0
  val_check_interval: 1.0
  deterministic: ${train.deterministic}

restore:
  ckpt_or_run_path: null
  mode: continue # null, finetune, hotstart, continue

monitor:
  metric: 'loss/train'
  mode: 'min'

callbacks:
  # - _target_: pytorch_lightning.callbacks.EarlyStopping
  #   patience: 42
  #   verbose: False
  #   monitor: ${train.monitor.metric}
  #   mode: ${train.monitor.mode}

  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 1
    verbose: False
    monitor: null
    mode: ${train.monitor.mode}
    every_n_epochs: 50
    save_last: True

  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
    log_momentum: False

  - _target_: pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar
    refresh_rate: 20

logging:
  upload:
    run_files: true
    source: true

  logger:
    _target_: pytorch_lightning.loggers.WandbLogger

    project: ${core.project_name}
    entity: null
    log_model: ${..upload.run_files}
    mode: 'online'
    tags: ${core.tags}

  wandb_watch:
    log: 'all'
    log_freq: 100
