dataset_name: cifar100_tasks # cifar100

data_path: ${oc.env:PROJECT_ROOT}/data/cifar100_tasks/same_classes_disj_samples/partition-1
output_path: ${oc.env:PROJECT_ROOT}/output

data:
  _target_: ccmm.data.task_datamodule.SameClassesDisjSamplesDatamodule
  data_path: ${nn.data_path}
  only_use_sample_num: -1 # -1 means use all samples

  gpus: ${trainer.trainer.gpus}

  num_workers:
    train: 8
    val: 8
    test: 8

  batch_size:
    train: 100
    val: 100
    test: 100

module:
  _target_: ccmm.pl_modules.pl_module.MyLightningModule
  model_name: ResNet_${nn.module.model.depth}_${nn.module.model.widen_factor}
  # model_name: ResNet18_PT
  # num_classes: ${dataset.num_classes}

  model:
    _target_: ccmm.models.resnet.ResNet
    depth: 22 # 22 or 50
    num_classes: ${dataset.num_classes}
    widen_factor: 2 # 2, 4, 16, 32 by git re-basin
    norm_layer: ln

  # model:
  #   _target_: ccmm.models.resnet_pt.ResNet18PreTrained
  #   num_classes: ${dataset.num_classes}

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    step_size: 3
    gamma: 0.1
