data_path: ${oc.env:PROJECT_ROOT}/data
output_path: ${oc.env:PROJECT_ROOT}/output

data:
  _target_: ccmm.data.datamodule.MyDataModule

  dataset: ${dataset}

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 100
    val: 512
    test: 512

module:
  _target_: ccmm.pl_modules.pl_module.MyLightningModule
  model_name: VGG16
  model:
    _target_: ccmm.models.vgg.VGG
    vgg_name: VGG16
    in_channels: ${dataset.in_channels}


  optimizer:
    _target_: torch.optim.SGD
    lr: 0.1
    # momentum: 0.9
    weight_decay: 5e-4 # checked in git-rebasin-s code (previously was 0.0005 for some reason)

  lr_scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 1
    max_epochs: ${train.trainer.max_epochs}
    warmup_start_lr: 1e-6 #1e-6
    eta_min: 0.0
    last_epoch: -1


  # optim.lr_scheduler.CosineAnnealingLR
